FROM ubuntu:focal

ARG STLINK_LINK=https://github.com/stlink-org/stlink/releases/download/v1.7.0/stlink_1.7.0-1_amd64.deb


# basics
RUN apt-get update && apt-get install -y \
    wget \
    make \
    cmake

RUN apt-get install -y build-essential
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -q -y \ 
    gcc-arm-none-eabi

RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -y -q \
    debhelper \
    pkg-config \
    libusb-1.0-0-dev

# RUN cd `mktemp -d` && wget ${STLINK_LINK} && dpkg --install `ls`

# build stlink from source
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -y -q \ 
    gcc build-essential cmake libusb-1.0 libusb-1.0-0-dev libgtk-3-dev git

RUN mkdir /stlink && cd /stlink && git clone https://github.com/stlink-org/stlink.git . && \
    make clean && \
    make release && \
    make install


# RUN make
# RUN make release