apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels: 
    {{- include "rabbitmq.labels" . | nindent 4 }}
data:
  # enabled_plugins: |
  #   [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s].
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672

    ##cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    ##cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    ##cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true
