apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
#   namespace: rabbits
subjects:
  - kind: ServiceAccount
    name: rabbitmq
#   namespace: rabbits
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq
