apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 4369
      targetPort: 4369
      name: discovery
    - port: 5672
      targetPort: 5672
      name: amqp
  selector: {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
